name: Master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Configure CI Git User
        run: |
          git config --global user.name "Joshua Avalon"
          git config --global user.email "git@avalon.sh"
          git remote set-url origin https://joshuaavalon:$GH_TOKEN@github.com/joshuaavalon/lambda-sharp
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Authenticate with registry
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
